#! /bin/sh

bspc monitor -d DVI-0 I II III IV V
bspc monitor -d DVI-1 VI VII VIII IX X


bspc config border_width        2
bspc config window_gap          14
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
compton -b
