#! /bin/sh

bspc config focus_follows_pointer true

primary="$(bspc query -M -m primary)"

bspc config -m "$primary" window_gap 14

bspc config border_width        3
bspc config top_padding         30
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc rule -a jetbrains- focus=on
bspc rule -a Pidgin monitor=^3
bspc rule -a Evolution monitor=^3

sxhkd &
polybar example &
bspwm-workspaces &
compton -C &
