#!/bin/zsh

next_to=$(bspc query -W -w "$1")
if [ -n  "$next_to" ]; then
	bspc window -f "$1"
	echo "if: $next_to"
else
	echo "else"
	cond=""
	ref=""
	if [[ "$1" = left ]]; then
		cond='[[ $upper_left_x -gt $ref ]]'
		ref=0
	else
		cond='[[ $upper_left_x -lt $ref ]]'
		ref=2000
	fi

	monitor=$(bspc query -M -m "$1")
	echo "Monitor: $monitor"
	if [[ -n  "$monitor" ]]; then
		edge_win=""
		for win in $(bspc query -m "$monitor" -W); do 
			upper_left_x=$(xwininfo -id "$win" | awk 'FNR==4 {print $4}')
			echo "$cond"
			if eval "$cond"; then
				edge_win="$win"
				ref="$upper_left_x"
			fi
		done
		bspc window -f "$edge_win"
	fi
fi
